services:
  db:
    image: postgres:14.17
    container_name: postgres-teslo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local