### POST Orthography check
POST {{ apiUrl }}/gpt/orthography-check
Content-Type: application/json

{
  "maxTokens": 2000,
  "prompt": "Hello"
}

### POST create products malformed payload
POST {{ apiUrl }}/products
Content-Type: application/json

{
  "brand": "Ford",
  "model": 1,
  "unknownField": "unknown"
}

### Patch update products
PATCH {{ apiUrl }}/products/6758a61c-b6d5-4b7b-8776-d230058576b6
Content-Type: application/json

{
  "name": "Pedro's product99",
  "price": 110.99,
  "images": [
    "image99"
  ]
}

### DELETE products
DELETE {{ apiUrl }}/products/{{productId}}
Authorization: Bearer {{token}}

