### POST Orthography check
POST {{ apiUrl }}/gpt/orthography-check
Content-Type: application/json

{
  "maxTokens": 200,
  "prompt": "¿Me puedes decir lá temperatura del sol?"
}

### POST pros-cons-discusser
POST {{ apiUrl }}/gpt/pros-cons-discusser
Content-Type: application/json

{
  "prompt": "¿Puedes comparar entre un carro o una moto?"
}

### POST pros-cons-discusser-stream
POST {{ apiUrl }}/gpt/pros-cons-discusser-stream
Content-Type: application/json

{
  "prompt": "¿Puedes comparar entre un carro o una moto?"
}

### POST translate
POST {{ apiUrl }}/gpt/translate
Content-Type: application/json

{
  "prompt": "¿Puedes comparar entre un carro o una moto?",
  "lang": "Árabe"
}

### POST Text to audio
POST {{ apiUrl }}/gpt/text-to-audio
Content-Type: application/json

{
  "prompt": "¿Puedes comparar entre un carro o una moto?",
  "lang": "Árabe",
  "voice": "nova"
}
