### POST Orthography check
POST {{ apiUrl }}/gpt/orthography-check
Content-Type: application/json

{
  "maxTokens": 200,
  "prompt": "¿Me puedes decir lá temperatura del sol?"
}

### POST pros-cons-discusser
POST {{ apiUrl }}/gpt/pros-cons-discusser
Content-Type: application/json

{
  "prompt": "¿Puedes comparar entre un carro o una moto?"
}

### POST pros-cons-discusser-stream
POST {{ apiUrl }}/gpt/pros-cons-discusser-stream
Content-Type: application/json

{
  "prompt": "¿Puedes comparar entre un carro o una moto?"
}

### POST translate
POST {{ apiUrl }}/gpt/translate
Content-Type: application/json

{
  "prompt": "¿Puedes comparar entre un carro o una moto?",
  "lang": "Árabe"
}

### POST Text to audio
POST {{ apiUrl }}/gpt/text-to-audio
Content-Type: application/json

{
  "prompt": "La ciencia encuentra la clave de la longevidad en el ejercicio físico: ¿moverse más tiempo o con más intensidad?",
  "voice": "nova"
}

### GET Text to audio
GET {{ apiUrl }}/gpt/text-to-audio/1747517358959

### Audio to text
POST {{ apiUrl }}/gpt/audio-to-text
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="prompt"

"Manten todos los signos de puntuación, interjecciones y onomatopeyas"
--WebAppBoundary
Content-Disposition: form-data; name="audio"; filename="El-parque.m4a"
Content-Type: audio/m4a

< ./El-parque.m4a
--WebAppBoundary--


### GET image-generation
GET {{ apiUrl }}/gpt/image-generation/1747907364478

### POST image-generation
POST {{ apiUrl }}/gpt/image-generation
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="prompt"

"Necesito una imagen de un personaje de dibujos animados"

--WebAppBoundary--

#--WebAppBoundary
#Content-Disposition: form-data; name="audio"; filename="El-parque.m4a"
#Content-Type: audio/m4a
#
#< ./El-parque.m4a


# curl --location '{{ apiUrl }}/gpt/image-generation'
#--header 'Content-Type: application/x-www-form-urlencoded'
#--data-urlencode 'prompt=Necesito una imagen de un personaje anime'
### POSTimage-generation
POST {{ apiUrl }}/gpt/image-generation
Content-Type: application/x-www-form-urlencoded

prompt = "Necesito una imagen de una ciudad estilo manga, de dia con coches y personas transitando por ella, algunas personas deben estar en primer plano y verse la cara con claridad, estar lo suficientemente cerca para que su figura ocupe 1/4 de la imagen,, todos ellos estilo manga, que sea en color y las caras tengan detalles de manga, el estilo manga debe estra inspirado en la serie GragonBall"


### Post Image variation
POST {{ apiUrl }}/gpt/image-variation
Content-Type: application/json

{
"baseImage": "{{ apiUrl }}/gpt/image-generation/1748343118376"
}

### POST Creat Thread
POST {{ apiUrl }}/gpt-assistant/create-thread
Content-Type: application/json

{
  "question": "Hola, como estas?"
}

### POST User Question
POST {{ apiUrl }}/gpt-assistant/user-question
Content-Type: application/json

{
  "threadId": "ABC",
  "Question": "Hola, como estas?"
}
