### GET list products
GET {{ apiUrl }}/products

### GET Paginated list products
GET {{ apiUrl }}/products?limit=2&offset=3

### GET products by uuid
GET {{ apiUrl }}/products/a8c78b3c-43da-42da-9a73-d57fcd22c256
### GET products by name
GET {{ apiUrl }}/products/pedros-product5
### GET products by Mongo Id
GET {{ apiUrl }}/products/pedro


### POST create products
POST {{ apiUrl }}/products
Content-Type: application/json

{
  "name": "Pedro's product",
  "sizes": ["small", "medium", "large"],
  "gender": "man"
}

### POST create products malformed payload
POST {{ apiUrl }}/products
Content-Type: application/json

{
  "brand": "Ford",
  "model": 1,
  "unknownField": "unknown"
}

### Patch update products
PATCH {{ apiUrl }}/products/329278b3-8c0a-449b-b3a0-e19da3ef1aca
Content-Type: application/json

{
  "name": "Pedro's product10",
  "price": 100,
  "description": "New description",
  "slug": "new slug2",
  "tags": ["firstTag"]

}

### DELETE products
DELETE {{ apiUrl }}/products/15b711fd-5438-486e-ba2f-a133494c1996

