### GET list products
GET {{ apiUrl }}/products

### GET Paginated list products
GET {{ apiUrl }}/products?limit=10&offset=30

### GET products by no
GET {{ apiUrl }}/products/1
### GET products by name
GET {{ apiUrl }}/products/ford
### GET products by Mongo Id
GET {{ apiUrl }}/products/{{testId}}


### POST create products
POST {{ apiUrl }}/products
Content-Type: application/json

{
  "name": "Pedro's product",
  "sizes": ["small", "medium", "large"],
  "gender": "man",
  "slug": "pedro-s-product"
}

### POST create products malformed payload
POST {{ apiUrl }}/products
Content-Type: application/json

{
  "brand": "Ford",
  "model": 1,
  "unknownField": "unknown"
}

### Patch update products
PATCH {{ apiUrl }}/products/{{testId}}
Content-Type: application/json

{
  "no": 2

}

### DELETE products
DELETE {{ apiUrl }}/products/67c78d4e84e0f96ed5a27ac7

