### Post upload product images
POST {{ apiUrl }}/files/product
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="nest.jpeg"
Content-Type: image/jpeg

< ./nest.jpeg
// < ./some.txt

### Get product images
GET {{ apiUrl }}/files/product/1473809-00-A_1_2000.jpg



