// Generated by Qodo Gen

import { AudioToTextDto } from './audio-to-text.dto';
import { validateSync } from 'class-validator';

describe('AudioToTextDto', () => {
  // Valid audio file is provided and successfully processed
  it('should validate when audio file is provided', () => {
    const dto = new AudioToTextDto();
    dto.audio = {
      fieldname: 'audio',
      originalname: 'recording.mp3',
      encoding: '7bit',
      mimetype: 'audio/mpeg',
      buffer: Buffer.from('audio content'),
      size: 1024,
    } as Express.Multer.File;
    dto.prompt = 'Transcribe this audio';

    const errors = validateSync(dto);

    expect(errors).toHaveLength(0);
  });

  // Audio file is missing or undefined
  it('should fail validation when audio file is missing', () => {
    const dto = new AudioToTextDto();
    dto.prompt = 'Transcribe this audio';

    const errors = validateSync(dto);

    expect(errors.length).toBeGreaterThan(0);
    expect(errors[0].property).toBe('audio');
    expect(errors[0].constraints).toHaveProperty('isDefined');
  });
});
