// Generated by Qodo Gen

import { ImageVariationDto } from './image-variation.dto';
import { validateSync } from 'class-validator';

describe('ImageVariationDto', () => {
  // Valid string input for baseImage is accepted
  it('should accept a valid string for baseImage', () => {
    // Create a new instance with the property set
    const validDto = Object.assign(new ImageVariationDto(), {
      baseImage: 'valid-image-data',
    });

    const errors = validateSync(validDto);

    expect(errors).toHaveLength(0);
  });

  // Empty string input for baseImage
  it('should reject an empty string for baseImage', () => {
    // Create a new instance with the property set
    const invalidDto = Object.assign(new ImageVariationDto(), {
      baseImage: '',
    });

    const errors = validateSync(invalidDto);

    expect(errors.length).toBeGreaterThan(0);
    expect(errors[0].property).toBe('baseImage');
    expect(errors[0].constraints).toHaveProperty('isNotEmpty');
  });
});
