// Generated by Qodo Gen

import { ImageGenerationDto } from './image-generation.dto';
import { validateSync } from 'class-validator';

describe('ImageGenerationDto', () => {
  // Valid ImageGenerationDto with only prompt field provided
  it('should validate when only prompt field is provided', () => {
    const dto = new ImageGenerationDto();
    dto.prompt = 'Generate a landscape image';

    const errors = validateSync(dto);

    expect(errors).toHaveLength(0);
  });

  // Empty string provided for prompt field
  it('should fail validation when empty string is provided for prompt', () => {
    const dto = new ImageGenerationDto();
    dto.prompt = '';

    const errors = validateSync(dto);

    expect(errors.length).toBeGreaterThan(0);
    expect(errors[0].property).toBe('prompt');
    expect(errors[0].constraints).toHaveProperty('isNotEmpty');
  });
});
