// Generated by Qodo Gen

import { OrthographyDto } from './orthography.dto';
import { validateSync } from 'class-validator';

describe('OrthographyDto', () => {
  // Valid object with required prompt string property
  it('should validate when prompt is provided', () => {
    const dto = new OrthographyDto();
    dto.prompt = 'Check this text';

    const errors = validateSync(dto);

    expect(errors).toHaveLength(0);
  });

  // Missing prompt property should fail validation
  it('should fail validation when prompt is missing', () => {
    const dto = new OrthographyDto();

    const errors = validateSync(dto);

    expect(errors.length).toBeGreaterThan(0);
    expect(errors[0].property).toBe('prompt');
    expect(errors[0].constraints).toHaveProperty('isString');
  });
});
