// Generated by Qodo Gen

import { ProsConsDiscusserDto } from './prosConsDiscusser.dto';
import { validateSync } from 'class-validator';

describe('ProsConsDiscusserDto', () => {
  // Valid string prompt is accepted
  it('should accept a valid string prompt', () => {
    const validDto = Object.assign(new ProsConsDiscusserDto(), {
      prompt: 'Should I buy a new car?',
    });

    const errors = validateSync(validDto);

    expect(errors).toHaveLength(0);
  });

  // Empty string as prompt
  it('should accept an empty string as prompt', () => {
    const emptyDto = Object.assign(new ProsConsDiscusserDto(), {
      prompt: '',
    });

    const errors = validateSync(emptyDto);

    expect(errors).toHaveLength(0);
  });
});
