// Generated by Qodo Gen

import { TextToAudioDto } from './text-to-audio.dto';
import { validate } from 'class-validator';

describe('TextToAudioDto', () => {
  // Valid TextToAudioDto with prompt and voice
  it('should validate when prompt and voice are provided', async () => {
    const dto = new TextToAudioDto();
    dto.prompt = 'Hello world';
    dto.voice = 'en-US-Neural2-F';

    const errors = await validate(dto);

    expect(errors).toHaveLength(0);
  });

  // Validation fails when prompt is missing
  it('should fail validation when prompt is missing', async () => {
    const dto = new TextToAudioDto();
    dto.voice = 'en-US-Neural2-F';

    const errors = await validate(dto);

    expect(errors.length).toBeGreaterThan(0);
    expect(errors[0].property).toBe('prompt');
    expect(errors[0].constraints).toHaveProperty('isString');
  });
});
