// Generated by Qodo Gen

import { TranslateDto } from './translate.dto';
import { validate } from 'class-validator';

describe('TranslateDto', () => {
  // Valid TranslateDto with both prompt and lang as strings
  it('should validate when prompt and lang are valid strings', () => {
    const dto = new TranslateDto();
    dto.prompt = 'Hello world';
    dto.lang = 'es';

    const errors = validate(dto);

    return expect(errors).resolves.toHaveLength(0);
  });

  // Empty strings for prompt or lang
  it('should validate when prompt and lang are empty strings', () => {
    const dto = new TranslateDto();
    dto.prompt = '';
    dto.lang = '';

    const errors = validate(dto);

    return expect(errors).resolves.toHaveLength(0);
  });
});
